const claim6y = {
  dateAdded: "",
  claimText: "Antizionism is a hate movement",
  claimShortText: "Intimidation",
  claimId: "6y"
}

const examples6y = [
  {
    dateAdded: "",
    date: "2024-04-01",
    claimIds: ["6y", "21"],
    exampleId: "6y02",
    keywordIds: [],
    text: "Teaneck, NJ yesterday. Anti-Israel, Pro Hamas anarchists shut down Rt 4 and intimidate an area of New Jersey where a large majority of Jews live.",
    standaloneTweets: ["1774880984413897179"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2023-10-25",
    claimIds: ["6y"],
    exampleId: "6y03",
    keywordIds: [],
    text: "Jewish students at Cooper Union are stuck in the library as protestors pound on the door. Eventually they needed a police escort to leave. Listen with sound on.",
    standaloneTweets: ["1717297845592821933", "1717307109539238281"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2024-06-11",
    claimIds: ["5", "6y", "6z", "18", "21", "22", "24"],
    exampleId: "6y04",
    keywordIds: [],
    text: "Antizionist mob takes over NYC subway: “Raise your hand if you’re a Zionist. This is your chance to get out.”",
    standaloneTweets: [],
    thenVsNowFormat: true,
    thenTweets: ["1800713713038590335"],
    nowTweets: ["1800652384558862784"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2023-11-10",
    claimIds: ["5", "6y", "6z", "18", "21", "22"],
    exampleId: "6y05",
    keywordIds: [],
    text: "Harvard pro-Palesinian students, including Harvard divinity student Elom Tettey-Tamaklo, surround, block the pathway, and scream in the face of a Jewish student.",
    standaloneTweets: ["1722970149769171274"],
    thenVsNowFormat: false,
    thenTweets: [],
    nowTweets: [],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2024-05-04",
    claimIds: ["5", "6y", "6z", "18", "21", "22", "24"],
    exampleId: "6y06",
    keywordIds: [],
    text: "A group of Palestine supporters at UPenn flash strobe lights in a Jewish student's eyes saying, 'If you know what’s good for you, you’ll get out of here' and 'Hope you have a good doctor.'",
    standaloneTweets: ["1786537278992482553"],
    thenVsNowFormat: false,
    thenTweets: [],
    nowTweets: [],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2024-06-29",
    claimIds: ["6y", "21", "22", "48a", "53"],
    exampleId: "6y07",
    keywordIds: [],
    text: "At 3 a.m., approximately 40 pro-Palestinian protesters gathered outside the home of U.S. Rep. Brad Schneider (D-IL), a Jewish congressman and vocal supporter of Israel. They chanted slogans, banged drums, and used noisemakers, waking residents including Schneider's family.",
    standaloneTweets: ["1807057782320894298"],
    thenVsNowFormat: false,
    thenTweets: [],
    nowTweets: [],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2023-12-12",
    claimIds: ["6y", "20", "22", "24"],
    exampleId: "6y08",
    keywordIds: [],
    text: "Pro-Hamas protesters threaten to kill Jewish attendees as they leave the Israeli Embassy's Hanukkah ceremony in Washington, DC. Watch as a woman screams, 'We will kill you all, occupiers.'",
    standaloneTweets: ["1807057782320894298"],
    thenVsNowFormat: false,
    thenTweets: [],
    nowTweets: [],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2023-12-08",
    claimIds: ["6y", "2", "3", "22", "25", "30y"],
    exampleId: "6y09",
    keywordIds: ["FreePalestine"],
    text: "A shooter yelled 'Free Palestine!' as he shot off a shotgun on the premises of Temple Israel and appeared to have torn down an Israeli flag or sign, according to law enforcement.",
    standaloneTweets: ["1733139538669641777"],
    thenVsNowFormat: false,
    thenTweets: [],
    nowTweets: [],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2025-07-28",
    claimIds: ["6y", "2", "3", "18", "30y"],
    exampleId: "6y10",
    keywordIds: ["FreePalestine"],
    text: "Jewish father and his 6 year old son attacked by raging mob screaming “Free Palestine!” and “Murderers, go home!” as they attempted to use a restroom in Milan, Italy. The father and son were wearing yarmulkas when the mob began attacking them.",
    standaloneTweets: ["1950095386644976018"],
    thenVsNowFormat: false,
    thenTweets: [],
    nowTweets: [],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2024-11-08",
    claimIds: ["6y", "2", "3", "18", "30y"],
    exampleId: "6y11",
    keywordIds: ["FreePalestine"],
    text: "Germany - 13 year old boys playing for a Jewish German soccer team were chased by grown men screaming “Free Palestine” and “fucking Jews” earlier today.",
    standaloneTweets: ["1855040240094003481"],
    source: true,
    sourceLink: "https://www.bild.de/regional/berlin/israel-hasser-greifen-spieler-von-tus-makkabi-in-berlin-an-672e03c5ebdb8724738ec456?wtmc=whtspp-shr&t_ref=https%3A%2F%2Ft.co%2F",
    thenVsNowFormat: false,
    thenTweets: [],
    nowTweets: [],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2025-12-14",
    claimIds: ["6y", "18", "30y"],
    exampleId: "6y12",
    keywordIds: ["FreePalestine"],
    text: "The California home of @CohenRodgir, who served in the U.S. Army, was brightly decorated for Chanukah. Assailants drove by, unloading 20 shots into the occupied family home while yelling “Free Palestine, N*gger, and “F- the Jews.” No injuries reported but the assailants have not yet been arrested.",
    standaloneTweets: ["2000290844662767910"],
    source: false,
    sourceLink: "",
    thenVsNowFormat: false,
    thenTweets: [],
    nowTweets: [],
    themTweets: [],
    usTweets: []
  }
]

module.exports = { claim6y, examples6y };