const claim25 = {
  dateAdded: "",
  claimText: "Beatings, stabbings, shootings, pogroms, bomb plots: these are the logical end of the system. Antizionism does not merely allow violence; it produces it. If the narrative is that “Zionists” embody evil, then violence becomes not just permitted but celebrated. (wording taken from The Movement Against Antizionism)",
  claimShortText: "Violence",
  claimId: "25"
}

const examples25 = [
  {
    dateAdded: "",
    date: "2025-06-01",
    claimIds: ["25"],
    exampleId: "0000025001",
    keywordIds: ["FreePalestine"],
    text: "Antizionist yells 'Free Palestine!' and throws Molotov cocktail at pro-Israelis marching peacefully to advcoate the release of the 50 Israeli hostages still being held in Gaza. One person was killed, and 12 people, inclduing children, were set on fire.",
    standaloneTweets: ["1929305592180748373", "1930526196724535475"],
    source: true,
    sourceLink: "https://www.theguardian.com/us-news/2025/jun/30/boulder-attack-victim-dies",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2023-12-22",
    claimIds: ["25"],
    exampleId: "0000025002",
    keywordIds: [],
    text: "Two Muslim men assault a group of Jewish women in London. The women were putting up posters of kidnapped Israelis.",
    standaloneTweets: ["1738277242394849518"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2024-01-23",
    claimIds: ["25"],
    exampleId: "0000025003",
    keywordIds: [],
    text: "Palestinian student at University of Central Florida arrested for threatening to shoot and kill 3 Jewish students.",
    standaloneTweets: ["1752140819660746997"],
    source: true,
    sourceLink: "https://www.wesh.com/article/ucf-palestinian-student-arrested-threat-jewish-students/46554538",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2024-01-29",
    claimIds: ["25"],
    exampleId: "0000025004",
    keywordIds: [],
    text: "Man arrested after brandishing knife at staff in Jewish supermarket. Suspect demanded that workers at shop in North London answer his questions about ‘events in Palestine’",
    standaloneTweets: ["1752132478704218553"],
    source: true,
    sourceLink: "https://www.telegraph.co.uk/news/2024/01/29/man-arrested-for-allegedly-brandishing-knife-in-jewish-shop/",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2024-06-23",
    claimIds: ["25", "20", "21", "2", "6y", "15"],
    exampleId: "0000025006",
    keywordIds: [],
    text: "Antizionist mobs gathered in masks outside a synogague in one of the most heavily Jewish neighborhoods in Los Angeles to block Jews from entering the synogague. Their justification was because the synogague was hosting an event selling land in Israel. Many brawls erupted, and one young Jewish man emerged with a bloody nose and face.",
    standaloneTweets: ["1804997197479686577"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2024-04-30",
    claimIds: ["25"],
    exampleId: "0000025007",
    keywordIds: [],
    text: "A young Jewish woman was knocked unconscious by pro-Hamas students at the UCLA encampments in California today.",
    source: true,
    sourceLink: "https://www.timesofisrael.com/liveblog_entry/pro-israel-protester-in-la-says-she-was-shoved-to-ground-hit-her-head-and-was-kicked/",
    standaloneTweets: ["1785427542012285429"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2024-11-06",
    claimIds: ["25", "3", "2", "5", "6y"],
    exampleId: "0000025008",
    keywordIds: [],
    text: "DePaul students Max Long, who served with the IDF to recover hostages, and Michael Kaminsky were physically assaulted from behind by masked Palestine supporters for holding an Israeli flag and offering dialogue about the Gaza conflict. The pro-Palestinian group Behind Enemy Lines is justifying this violent assault, calling it 'a tiny bit of justice.'",
    source: true,
    sourceLink: "https://abc7chicago.com/post/adam-erkan-pleads-guilty-battery-attack-jewish-students-depaul-university-lincoln-park-campus/18209306/",
    standaloneTweets: ["1856776918604869713"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2024-06-23",
    claimIds: ["25", "5", "6y", "18"],
    exampleId: "0000025009",
    keywordIds: ["FreePalestine"],
    text: "NYC Jewish family pummeled at 5th-grade commencement by attendees shouting 'Free Palestine'",
    source: true,
    sourceLink: "https://nypost.com/2024/06/23/us-news/nyc-jewish-family-pummeled-at-5th-grade-commencement-by-attendees-shouting-free-palestine-mom-says/?utm_campaign=nypost&utm_source=twitter&utm_medium=social",
    standaloneTweets: ["1804817134192570558"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2023-11-07",
    claimIds: ["25"],
    exampleId: "0000025010",
    keywordIds: [],
    text: "Paul Kessler, a 69-year-old Jewish pro-Israel activist, was fatally assaulted during a counter-protest to a pro-Palestinian rally in Thousand Oaks, California. He was struck in the head with a megaphone by college professor Loay Alnaji, (later charged with involuntary manslaughter), fell and hit his head on the ground, suffering a fatal brain hemorrhage. His death was ruled a homicide on November 7, 2023",
    source: false,
    sourceLink: "",
    standaloneTweets: ["1721911382105268267"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2025-09-20",
    claimIds: ["25"],
    exampleId: "0000025011",
    keywordIds: ["FreePalestine"],
    text: "Witness says one shooter yelled 'Free Palestine' before firing upon Nashua Country Club event attendees",
    source: true,
    sourceLink: "https://patch.com/new-hampshire/nashua/witness-says-1-shooter-yelled-free-palestine-firing-upon-nashua-country-club",
    standaloneTweets: ["1969576650686836808"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2025-05-21",
    claimIds: ["25", "3", "5"],
    exampleId: "0000025012",
    keywordIds: ["FreePalestine"],
    text: "Antizionist killed two Israeli embassy staff members (one Christina, one Jewish) outside DC's Capital Jewish Museum. The male victim, Yaron Lischinsky, had bought an engagement ring planning to propose next week in Jerusalem to his girlfriend, Sarah Milgrim. Both were killed. The killer wore a keffiyeh and shouted 'Free, free Palestine!' upon being arrested. According to the charges, Sarah Milgrim, badly wounded, tried to crawl away. The killer followed her, firing repeatedly until he emptied his weapon and she was dead. Sarah Milgrim's friend: 'In three weeks Sarah and I were supposed to set out on a trip to build bridges between communities that often stand divided. The goal? Peace.'",
    source: false,
    sourceLink: "",
    standaloneTweets: ["1925414470156701949", "1925418002263978045", "1925671899603841322", "1926277255619133563", "1926258744087703696"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2023-12-12",
    claimIds: ["25", "2", "3", "5", "18"],
    exampleId: "0000025013",
    keywordIds: ["FreePalestine"],
    text: "Hateful attacker hurls rock at Jewish man in NYC, snarls 'Free Palestine'",
    source: false,
    sourceLink: "",
    standaloneTweets: ["1734660055738253494"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2025-12-14",
    claimIds: ["25", "6y", "6z", "31h", "31n"],
    exampleId: "0000025014",
    keywordIds: [],
    text: "2 dead, 12 injured at Brown University: The shooting took place in a popular economics course taught by Professor Rachel Friedberg. She is also affiliated with the Judaic Studies department, and previously taught at Hebrew University. The shooter specifically targeted this class. The study session was in an auditorium with stadium-seating. He entered from the top, shouted something (in Arabic, apparently), and began shooting. He killed 2 students and injured at least 12 others. The two killed were Ella Cook, 19, VP of the College Republicans, and Muhammad Aziz Umurzokov, 18, an Uzbeki immigrant who came to the US in 2011 and wanted to be a neurosurgeon.",
    source: true,
    sourceLink: "https://www.oceanstatemedia.org/news-and-culture/active-shooter-reported-at-brown-university",
    standaloneTweets: ["2000246395937169853", "2000236654917800251", "2000413832594985422", "2000641322814992701"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2025-10-03",
    claimIds: ["25", "6z", "30", "31h"],
    exampleId: "0000025015",
    keywordIds: ["PoliceFailure"],
    text: "Islamic t*rrorist Jihad al-Shami rammed his car into a crowd of Jews attending synagogue on Yom Kippur in Manchester, then pulled out a knife. Two people, Adrian Daulby, 53, and Melvin Cravitz, 66, were killed, and four seriously injured. Police were found to be responsible for shooting two of the victims, including one who was killed, as they were trying to neutralize the attacker. The attacker's father priased Hamas on Oct. 7, calling them 'Allah's men on Earth'. The attacker was a Syrian asylum seeker out on bail and being charged with rape.",
    source: true,
    sourceLink: "https://www.bbc.com/news/articles/cn98jnr5jpzo",
    standaloneTweets: ["1973906188543643826", "1974507738660208757", "1974118868290580888", "1974212375646712073", "1974210268432368024"],
    themTweets: [],
    usTweets: [],
    additionalNotes: ["Attacker was out on bail for a rape charge from earlier in the year", "Syrian asylum seeker in the UK", "Police shot and killed two of the victims as they were trying to neutralize the attacker", "Father priased Hamas on Oct. 7, calling them 'Allah's men on Earth'", "Father who praised Hamas is a surgeon"]
  },
  {
    dateAdded: "",
    date: "2025-12-14",
    claimIds: ["25", "6z", "31h"],
    exampleId: "0000025016",
    keywordIds: ["PoliceFailure"],
    text: "Bondi Beach, Australia: At least 12 people have been killed and 29 others injured in a shooting at a Jewish event on the first night of Hannukah. The shooters were a Pakistani father and son with ties to ISIS. Multiple eyewitnesses said police hid during the shooting and did not return fire. The third Tweet below shows horrific scenes at the shooting and viewer discretion is strongly advised. The fourth Tweet below shows video of the heroic civilian (a local Muslim man) disarming one of the shooters.",
    source: true,
    sourceLink: "https://www.cnn.com/world/live-news/bondi-beach-gunshots-reported-12-14-25?Date=20251214",
    standaloneTweets: ["2000361412187902310", "2000493078700839027", "2000123984013398066", "2000194500229005765", "2000171267102826758"],
    themTweets: [],
    usTweets: [],
    additionalNotes: ["Multiple eyewitnesses said police did not return fire during the attack, hiding behind obstructions"]
  },
  {
    dateAdded: "",
    date: "2025-12-16",
    claimIds: ["25", "6z"],
    exampleId: "0000025017",
    keywordIds: [],
    text: "Video shows disturbing antisemitic attack on NYC subways: ‘Fuck the Jews’",
    source: true,
    sourceLink: "https://nypost.com/2025/12/16/us-news/jews-attacked-on-nyc-subway-nypd-investigating-as-hate-crime/?utm_medium=social&utm_social_post_id=624763471&utm_campaign=nypost&utm_source=twitter&utm_social_handle_id=17469289",
    standaloneTweets: ["2000985482767773940"],
    themTweets: [],
    usTweets: [],
    additionalNotes: []
  }
]

module.exports = { claim25, examples25 };