const claim31c = {
  dateAdded: "",
  claimText: "DARVO is a practice of narcissists. It stands for Deny, Accuse, Reverse Victim and Offender. It is also a common feature of the antizionist crowd.",
  claimShortText: "DARVO",
  claimId: "31c"
}

const examples31c = [
  // {
  //   dateAdded: "",
  //   date: "2023-10-13",
  //   claimIds: ["31c", "31a", "47", "16"],
  //   exampleId: "00000031c01",
  //   keywordIds: [],
  //   text: "This deep dive (LINK) shows how antizionists demanded proof of dead babies, then turned that proof into fraudulant claims of Israeli lies.",
  //   deepDive: true,
  //   standaloneTweets: ["1712808899064070296"],
  //   themTweets: [],
  //   usTweets: []
  // },
  {
    dateAdded: "",
    date: "2023-12-27",
    claimIds: ["31c"],
    exampleId: "00000031c02",
    keywordIds: [],
    text: "Leaflets are dropped in a Dutch mall: 'This is how the oppressive Israeli Army notifies Gazans of their imminent death by dropping papers over their heads.' Leaflets are of course used by the IDF to warn civilians to vacate the location of an upcoming strike, a practice meant to prevent civlian casualties.",
    deepDive: false,
    standaloneTweets: ["1740122472945475953"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2026-01-12",
    claimIds: ["31c"],
    exampleId: "00000031c03",
    keywordIds: [],
    text: "Karim Younis, who shot a hitchhiker in the head, is portrayed as a victim.",
    deepDive: false,
    source: true,
    sourceLink: "https://www.jns.org/israels-longest-serving-security-prisoner-released-after-completing-40-year-sentence/",
    standaloneTweets: [],
    themTweets: ["2010823609829277991"],
    usTweets: ["2010944631849299997"]
  },
  {
    dateAdded: "",
    date: "2026-01-27",
    claimIds: ["31c", "17", "30x"],
    exampleId: "00000031c04",
    keywordIds: [],
    text: "Renowned antizionist Nerdeen Kiswani, close advisor to Zohran Mamdani, is bothered by how casually 'Zionists' are 'inventing' death toll figures in Iran, which are based on opposition figure estimates. 'Suddenly,' she writes, 'we’re expected to accept an enormous number of people killed in Iran within the span of weeks, with no evidence, no independent verification, no sustained reporting . And we’re supposed to suspend every standard of skepticism we were told was sacred.' Yet she has no problem promoting and mourning insanely inflated numbers of those killed in Gaza using the same standard she is so 'bothered by' when it comes to Iran. 'What matters is controlling the narrative: when death is real, when it’s fake, when numbers count, and when they don’t.' Indeed.",
    deepDive: false,
    source: false,
    standaloneTweets: [],
    thenVsNowFormat: true,
    thenTweets: ["2016372890568921249", "1972704175000629634"],
    nowTweets: ["2016255362450505807", "2015693913273536939"]
  },
  {
    dateAdded: "",
    date: "2023-11-11",
    claimIds: ["31c", "17"],
    exampleId: "00000031c05",
    keywordIds: [],
    text: "Mass murderer Bashar al-Assad, Assad condemns Israel and demands that the Palestinians be protected at the “Emergency Meeting” of the Arab League and the Organisation of Islamic Corporation in the Saudi Capital to discuss the Hamas-Israel war. Video 2:  Execution of dozens of  civilians in Syria by members of military Syrian intelligence. Unarmed civilians are taken blindfolded one by one to a pit in a suburb of Damascus,Tadamon. There they are shot in the head. “Greetings to the boss [teacher],” says one of the two perpetrators, smiling into the camera.",
    deepDive: false,
    source: true,
    sourceLink: "https://www.syriahr.com/en/291981/",
    standaloneTweets: [],
    thenVsNowFormat: false,
    themTweets: ["1723340264163426514"],
    usTweets: ["1740976877651517934", "1723671780164841946"]
  },
  {
    dateAdded: "",
    date: "2026-06-08",
    claimIds: ["31c", "17", "15"],
    exampleId: "00000031c06",
    keywordIds: ["Graham Platner"],
    text: "Leftists says she’s OK with the Nazi tattoo, but if he had an Israeli flag tattoo that would be a deal breaker for her because then he would support genocide…..",
    deepDive: false,
    source: false,
    standaloneTweets: [],
    thenVsNowFormat: false,
    themTweets: ["2064544415998492888"],
    usTweets: ["2064527638593450197"]
  },
  {
    dateAdded: "",
    date: "2026-08-10",
    claimIds: ["31c"],
    exampleId: "00000031c07",
    keywordIds: [],
    text: "Yoseph Haddad was ATTACKED in the MOST COWARDICE way and during a DEBATE! You have him being grabbed UNPROVOKED, attacked from BEHIND, others trying to STEP IN to fight Yoseph, and some dude claiming victim after it didn't go their way LMAO",
    deepDive: false,
    source: false,
    standaloneTweets: ["2087017973919965602"],
    thenVsNowFormat: false,
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2026-09-19",
    claimIds: ["31c", "13", "31a"],
    exampleId: "00000031c08",
    keywordIds: [],
    text: "BOMBSHELL: Motaz Azaiza admits he filmed Israeli hostages being beaten in the streets of Gaza on October 7, and deliberately never published it, to protect the identities of the people beating them. Azaiza is an influential 'photojournalist' from Ghazza. TIME named him to the TIME 100. He was nominated for the 2024 Nobel Peace Prize. CNN, the Guardian and Sky all interviewed him. Ms. Rachel Griffin-Accurso, who has 16 million subscribers, made a video for preschoolers introducing 'my friend Motaz.' She deleted it later.",
    deepDive: false,
    source: false,
    standaloneTweets: [],
    thenVsNowFormat: true,
    thenTweets: ["2101098330369700327"],
    nowTweets: ["2100991727595049171", "2101414389094011220"]
  },
  {
    dateAdded: "",
    date: "2026-09-19",
    claimIds: ["31c", "13", "31a"],
    exampleId: "00000031c09",
    keywordIds: ["Zohran Mamdani"],
    text: "Just the mayor of New York meeting multiple times with a man (Motaz Azaiza) who admitted being in Hamas groups to coordinate propaganda, and who filmed Hamas terrorists kidnapping and torturing Israeli civilians (but didn’t take part because he didn’t want to be killed).",
    deepDive: false,
    source: false,
    standaloneTweets: [],
    thenVsNowFormat: true,
    thenTweets: ["2101664242139107328"],
    nowTweets: ["2100991727595049171", "2101414389094011220"]
  },
  {
    dateAdded: "",
    date: "2026-03-23",
    claimIds: ["31c", "17"],
    exampleId: "00000031c10",
    keywordIds: ["Britain", "UK", "United Kingdom", "London", "Golders Green"],
    text: "“British Muslims are scared,” says Sadiq Khan - after FOUR Jewish communities had their voluntary ambulance services torched.",
    deepDive: false,
    source: false,
    standaloneTweets: [],
    thenVsNowFormat: true,
    thenTweets: ["2036012509270880767"],
    nowTweets: ["2036016151998709999", "2036133501687242996"]
  },
  {
    dateAdded: "",
    date: "2008-02-29",
    claimIds: ["31c", "30x", "31k", "31g"],
    exampleId: "00000031c11",
    keywordIds: ["We teach life"],
    text: "Hamas leader Fathi Hammad: '[The enemies of Allah] do not know that the Palestinian people has developed its [methods] of death and death-seeking. For the Palestinian people, death has become an industry, at which women excel, and so do all the people living on this land. The elderly excel at this, and so do the mujahideen and the children. This is why they have formed human shields of the women, the children, the elderly, and the mujahideen, in order to challenge the Zionist bombing machine. It is as if they were saying to the Zionist enemy: We desire death like you desire life.'",
    deepDive: false,
    source: false,
    standaloneTweets: [],
    thenVsNowFormat: true,
    thenTweets: ["2021612189325340896"],
    nowTweets: ["2021423403505418394"]
  }
]

module.exports = { claim31c, examples31c };