const claim31e = {
  dateAdded: "",
  claimText: "Palestinians train their children from a young age to kill Jews",
  claimShortText: "Child terrorists",
  claimId: "31e"
}

const examples31e = [
  {
    dateAdded: "",
    date: "2025-11-17",
    claimIds: ["31e"],
    exampleId: "3701",
    keywordIds: [],
    text: "A compilation of videos of Palestinian children being trained to kill Jews",
    standaloneTweets: ["1990497743350214963"],
    source: false,
    sourceLink: "",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2019-05-27",
    claimIds: ["31e"],
    exampleId: "31e02",
    keywordIds: [],
    text: "Boy taught to shoot at Jews - 'the enemy' - in special Ramadan series, 'Children of the Village Chief,' broadcast on PA TV about Arab village",
    standaloneTweets: ["1133000088991784960"],
    source: false,
    sourceLink: "",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2021-01-31",
    claimIds: ["31e"],
    exampleId: "31e02",
    keywordIds: [],
    text: "A 17-yr-old Palestinian terrorist tries to kill an Israeli soldier, prompting another to shoot him to prevent the attack. Within 12 hours he has been branded a 'martyr,' and his death repackaged as an 'execution.'",
    standaloneTweets: ["1355790376515346433"],
    source: false,
    sourceLink: "",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2017-05-03",
    claimIds: ["31e", "31d"],
    exampleId: "31e03",
    keywordIds: [],
    text: "Hamas teaches children 'to shoot Jews' - 'all of them' (2014)",
    standaloneTweets: ["859730788723691526"],
    source: false,
    sourceLink: "",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2024-08-08",
    claimIds: ["31e"],
    exampleId: "31e04",
    keywordIds: [],
    text: "The Palestinians named their largest summer camp - which hosts 150 children ages 7-13 - after Salah Khalaf, the mastermind behind the 1972 Munich massacre, and taught kids to chant: 'We’re on your path, Salah Khalaf!'",
    standaloneTweets: ["1827701778172756344", "1169565842909982732"],
    source: true,
    sourceLink: "https://palwatch.org/page/35443",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2024-09-05",
    claimIds: ["31e", "31d"],
    exampleId: "31e05",
    keywordIds: [],
    text: "A compilation of videos on Palestinian TV where children call Jews the sons of pigs and apes.",
    standaloneTweets: ["1831615943199318290"],
    source: false,
    sourceLink: "",
    themTweets: [],
    usTweets: []
  },
    {
    dateAdded: "",
    date: "2024-09-19",
    claimIds: ["31e"],
    exampleId: "31e03",
    keywordIds: [],
    text: "Teaching kids to shoot Israelis, then teens to shoot even Palestinians.",
    standaloneTweets: ["1836882769172967566"],
    source: false,
    sourceLink: "",
    themTweets: [],
    usTweets: []
  },
   {
    dateAdded: "",
    date: "2023-08-03",
    claimIds: ["31e"],
    exampleId: "31e04",
    keywordIds: [],
    text: "Fatah Summer camp two months before Oct. 7 trained children to commit Oct. 7-like atrocities.",
    standaloneTweets: ["1809884833977356571"],
    source: false,
    sourceLink: "",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2023-10-01",
    claimIds: ["31e"],
    exampleId: "31e05",
    keywordIds: [],
    text: "This video was made by Hamas teen terrorist Muhammad Rummana who was killed while throwing a Molotov cocktail on Friday night.",
    standaloneTweets: ["1708468659906101640"],
    source: false,
    sourceLink: "",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2023-10-01",
    claimIds: ["31e"],
    exampleId: "31e05",
    keywordIds: [],
    text: "This video was made by Hamas teen terrorist Muhammad Rummana who was killed while throwing a Molotov cocktail on Friday night.",
    standaloneTweets: ["1708468659906101640"],
    source: false,
    sourceLink: "",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2022-07-25",
    claimIds: ["31e"],
    exampleId: "31e06",
    keywordIds: [],
    text: "Kids at Palestinian camp chant 'We will die and Palestine will live'",
    standaloneTweets: ["1809904464528109958"],
    source: false,
    sourceLink: "",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2024-07-01",
    claimIds: ["31e"],
    exampleId: "31e07",
    keywordIds: [],
    text: "In July 2024, a child in Gaza proudly explains what he learns in school, how to kill Jews.",
    standaloneTweets: ["1986070983355056574"],
    source: false,
    sourceLink: "",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2021-06-29",
    claimIds: ["31e", "31k"],
    exampleId: "31e08",
    keywordIds: [],
    text: "In June 2021, a child at Islamic Jihad Gaza Summer Camp: 'Hitler Left Some of You Alive to Show Us How Wicked You Are; We Will Tear Your Bodies Apart with Our Rockets.' PIJ Official: 'The children of Palestine Will Sacrifice Their Blood and Body Parts.'",
    standaloneTweets: ["1986070983355056574"],
    source: false,
    sourceLink: "",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2023-05-10",
    claimIds: ["31e"],
    exampleId: "31e09",
    keywordIds: [],
    text: "Gaza Strip: Palestinian children cheer with joy at the sight of rockets being launched at Israel",
    standaloneTweets: ["1656343848346320906", "1719404208569635237"],
    source: false,
    sourceLink: "",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2023-05-10",
    claimIds: ["31e"],
    exampleId: "31e10",
    keywordIds: [],
    text: "Gaza children are encouraged to cheer on a roof as Israeli civilian centers are bombed by Gaza terror organizations.",
    standaloneTweets: ["1656311960944918529"],
    source: false,
    sourceLink: "",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2025-12-20",
    claimIds: ["31e", "31f", "31g", "31k"],
    exampleId: "31e11",
    keywordIds: [],
    text: "Reporter: 'If your daughter decides she wants to blow herself up, will you be happy about that?' Palestinian father: 'I will help her and encourage her.' (Unable to find original air date of clip.)",
    standaloneTweets: ["2002245074068095349"],
    source: false,
    sourceLink: "",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2024-07-11",
    claimIds: ["31e", "31g", "31j", "31k"],
    exampleId: "31e12",
    keywordIds: [],
    text: "Kutaiba Hatab, student at UNRWA’s Jalazone school, directly funded by US taxpayers. His UNRWA school teaches him to “keep fighting until Palestine is liberated.” His dream: to “be a jihadist,” kill Jews for Allah, and “become a martyr.”",
    standaloneTweets: ["1818980888492790216"],
    source: false,
    sourceLink: "",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2025-01-11",
    claimIds: ["31e", "31l"],
    exampleId: "31e13",
    keywordIds: [],
    text: "Children of ISIS fighters in Syria start attacking NBC News reporter Richard Engel, threatening to kill him. This is what Radical Islamist child indoctrination looks like. And Hamas is exactly the same as ISIS.",
    standaloneTweets: ["1890958696697471011"],
    source: false,
    sourceLink: "",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2016-07-23",
    claimIds: ["31e"],
    exampleId: "31e14",
    keywordIds: [],
    text: "Palestinian youth demonstrate skills on a military graduation ceremony in a Hamas organized summer camp in Gaza.",
    standaloneTweets: ["756782424017739777"],
    source: false,
    sourceLink: "",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2023-05-27",
    claimIds: ["31e"],
    exampleId: "31e15",
    keywordIds: [],
    text: "Graduation of the Young Deers Kindergarten in Beit Hanoun, north Gaza Strip. Children are trained for war.",
    standaloneTweets: ["1662528477986443264"],
    source: true,
    sourceLink: "https://www.facebook.com/alghazalan/videos/%D8%B9%D8%B1%D9%88%D8%B6%D9%86%D8%A7-%D9%84%D8%A7-%D8%AA%D9%86%D8%AA%D9%87%D9%8A-%D9%88%D9%84%D9%83%D9%86-%D9%86%D9%86%D8%AA%D8%B8%D8%B1-%D8%A7%D9%84%D8%B9%D8%B1%D8%B6-%D8%A7%D9%84%D8%A3%D9%82%D9%88%D9%89-%D8%A7%D9%84%D8%B9%D8%B1%D8%B6-%D8%A7%D9%84%D8%B9%D8%B3%D9%83%D8%B1%D9%8A%D9%85%D8%B9-%D9%86%D8%AE%D8%A8%D8%A9-%D9%85%D9%86-%D8%A7%D9%84%D8%B9%D8%B3%D8%A7%D9%83%D8%B1-%D8%A7%D9%84%D8%B5%D8%BA%D9%8A%D8%B1%D8%A9-/940565537154474/",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2018-05-18",
    claimIds: ["31e"],
    exampleId: "31e16",
    keywordIds: ["children"],
    text: "This is the graduation ceremony of a Hamas kindergarten in Gaza. This is how Palestinian toddlers are brainwashed to kill. They were trained for this show by real Hamas terrorists, as the video shows. Hamas trains kids as killers, just like ISIS.",
    standaloneTweets: ["1001161618867269634"],
    source: false,
    sourceLink: "",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2023-12-24",
    claimIds: ["31e"],
    exampleId: "31e17",
    keywordIds: ["children"],
    text: "Hamas terrorists teach a child (yes a child) to shoot a rifle. The footage uncovered by the IDF is believed to be from a summer camp run by the terrorist organization.",
    standaloneTweets: ["1738896810184204299"],
    source: false,
    sourceLink: "",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2007-05-31",
    claimIds: ["31e", "31k"],
    exampleId: "31e18",
    keywordIds: [],
    text: "Young children are shown wearing military uniforms and carrying rifles. Some wear masks and suicide vests. The children are shown marching in formation, crawling on the ground, jumping over obstaces, and shouting slogans. Children chant: 'Jihad! Allah Akbar! Your role model? The Prophet [Muhammad]. Your path? Jihad! Your aspiration? Death for Allah. Your movement? Hamas! Your movement? Hamas!'",
    standaloneTweets: ["1805332984179945824"],
    source: true,
    sourceLink: "https://www.youtube.com/watch?v=vRuuDI0KCR8",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2023-07-14",
    claimIds: ["31e"],
    exampleId: "31e19",
    keywordIds: [],
    text: "At Hamas 'Shield of Jerusalem' summer camps, children undergo military training, learn to handle real weapons such as assault rifles, sniper rifles, machine guns, and RPGs, simulate raiding Israeli military posts and conquering Jerusalem.",
    standaloneTweets: ["1829401505687846956"],
    source: false,
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2021-07-03",
    claimIds: ["31e"],
    exampleId: "31e20",
    keywordIds: [],
    text: "Children from one the military summer camps (likely Hamas) demonstrate their military skills in front of an audience. In one scene, they capture an IDF base via a tunnel, and successfully abduct an Israeli soldier. One child wears a GoPro mimicking the gear militants wear.",
    standaloneTweets: ["1411569357306560512"],
    source: true,
    sourceLink: "https://www.facebook.com/101012308830875/videos/395568101894334/",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2015-01-30",
    claimIds: ["31e"],
    exampleId: "31e21",
    keywordIds: [],
    text: "15,000 young Gazans complete Hamas terror training camps - Times of Israel",
    standaloneTweets: ["570555020313272320"],
    source: true,
    sourceLink: "https://www.jpost.com/arab-israeli-conflict/gazan-youth-graduate-hamas-military-training-camp-389438",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2015-01-30",
    claimIds: ["31e"],
    exampleId: "31e21",
    keywordIds: ["children"],
    text: "17,000 young Gazans complete Hamas terror training camps - Jerusalem Post",
    standaloneTweets: ["561216517245652992"],
    source: true,
    sourceLink: "https://www.jpost.com/arab-israeli-conflict/gazan-youth-graduate-hamas-military-training-camp-389438",
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2015-07-25",
    claimIds: ["31e"],
    exampleId: "31e22",
    keywordIds: ["children"],
    text: "Hamas opens military camp for 25,000 Gazans aged 15 and up.",
    standaloneTweets: ["625017248910983168"],
    source: true,
    sourceLink: "https://www.timesofisrael.com/hamas-gives-25000-gazans-combat-training",
    themTweets: [],
    usTweets: []
  }
]

module.exports = { claim31e, examples31e };