const claim30x = {
  dateAdded: "",
  claimText: "Antizionists: They mourn our deaths, then celebrate and justify them. They offer well wishes, then accusations and libels. They play rhetorical games only capable of psychopaths.",
  claimShortText: "Rhetorical games",
  claimId: "30x"
}

const examples30x = [
  {
    dateAdded: "",
    date: "2025-01-01",
    claimIds: ["30x"],
    exampleId: "00000000A",
    keywordIds: ["JeremyCorbyn"],
    text: "Jeremy Corbyn, once a leader of the UK labor party, a notorious antizionist, is 'horrified' by the stabbing attack at a Manchester synogogue on Yom Kippur, killing two Jews and injuring four more. Yet he has promoted and attended the antizionist hate marches in Britain, calls Hezbollah and Hamas his 'friends', and laid a wreath at the tomb of the perpetrators of the 1972 Munich Massacre which mutilated and killed 11 Israeli Olympic athletes.",
    source: false,
    sourceLink: "",
    standaloneTweets: [],
    thenVsNowFormat: true,
    thenTweets: ["1973741100100899131", "1817307796649447615", "1724177765174214943"],
    nowTweets: ["1973724447963337178"]
  },
  {
    dateAdded: "",
    date: "2025-11-20",
    claimIds: ["30x", "15", "6"],
    exampleId: "00000030x01",
    keywordIds: ["CAIR"],
    text: "Northwestern University, in a settlement with the government over violations of the Civil Rights Act against Jewish students, was required to give antisemitism training. CAIR sued the university, saying focing students to learn about antisemitism is 'anti-Palestinian racism.' 'So now talking about Jewish identity, that's an act of discrimination' -- Yael Lerman, Director of Stand With Us Law. See her video below.",
    source: false,
    sourceLink: "",
    standaloneTweets: ["1991731782920860140"],
    thenVsNowFormat: false,
    thenTweets: [],
    nowTweets: []
  },
  {
    dateAdded: "",
    date: "2025-11-26",
    claimIds: ["30x", "31a", "31c", "31e"],
    exampleId: "00000030x02",
    keywordIds: [],
    text: "The 19-year-old Palestinian Shorouq Dwayyat was just a child who was defending herself from a settler trying to remove her hijab. Apparently she just happend to have a knife on her at the time and stabbed a Jewish man in the neck/head & went for another before being shot then was treated in an Israel hospital. And wrote about how she wanted to die for the Palestinian cause on social media.",
    source: false,
    sourceLink: "",
    standaloneTweets: ["1728658600678027710"],
    thenVsNowFormat: false,
    thenTweets: [],
    nowTweets: []
  },
  {
    dateAdded: "",
    date: "2023-11-28",
    claimIds: ["30x", "1", "2", "3", "15", "16", "17", "21", "28", "31c", "46"],
    exampleId: "00000030x03",
    keywordIds: [],
    text: "The Oakland City Council voted on a resolution to call for a ceasefire. A city council member tried to insert language condemning Hamas. This was the reaction:'There have not been beheadings of babies and rapings.' 'Calling Hamas terrorist is ridiculous, racist, and plays into genocidal propoganda.' 'The IDF killed most of the people on that day.' 'Asking to condemn Hamas is anti-Arab racism' 'That this was a massacre of Jews is a fabricated narrative.' 'Did anyone notice that those who oppose this resolution are old white supremacists?' 'Hamas is a resistance organization fighting for liberation.'",
    source: false,
    sourceLink: "",
    standaloneTweets: ["1729630529199432095"],
    thenVsNowFormat: false,
    thenTweets: [],
    nowTweets: []
  },
  {
    dateAdded: "",
    date: "2024-02-02",
    claimIds: ["30x", "30"],
    exampleId: "00000030x04",
    keywordIds: [],
    text: "'Peaceful' UCLA encampments left a Jewish woman knocked unconscious and denied Zionist students entry to classes and the campus library",
    source: false,
    sourceLink: "",
    standaloneTweets: [],
    thenVsNowFormat: false,
    themTweets: ["1785994376725811303"],
    usTweets: ["1785427542012285429", "1785145131097632826"]
  },
  {
    dateAdded: "",
    date: "2024-02-02",
    claimIds: ["30x", "53"],
    exampleId: "00000030x05",
    keywordIds: [],
    text: "Mel Buer (independent journalist with discontinued X account): 'UCPD hangs up on students as Zionists brutally attack the [UCLA encampment].' This comes after the encampment itself attacked police. Then they're demanding police protection from the 'brutal' Zionist attack. Meanwhile, the 911 call hardly shows people in the middle of an emergency. It shows petulent children demanding Univesity of California 911 dispatch stay on the line so they can 'ask questions,' while the dispatcher explains she has actual emergencies she needs to attned to.",
    source: false,
    sourceLink: "",
    standaloneTweets: [],
    thenVsNowFormat: false,
    themTweets: ["1788487039933178080"],
    usTweets: ["1786059817347641640", "1788495464352174243"]
  },
  {
    dateAdded: "",
    date: "2025-02-25",
    claimIds: ["30x", "1", "2", "3", "4", "18", "52"],
    exampleId: "00000030x06",
    keywordIds: [],
    text: "The Orwellian liberal utopian edict to 'be kind' could not be more perfectly encapsulated than in this self-justifying Naziesque reality-inverting email, which is then signed 'Kindly.' Combined with her smiling photo, it's extremely dark.",
    source: false,
    sourceLink: "",
    standaloneTweets: ["1894619709716267479"],
    thenVsNowFormat: false,
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2024-06-28",
    claimIds: ["30x", "3"],
    exampleId: "00000030x07",
    keywordIds: [],
    text: "From Brian's Psychology Today profile: 'I strive to create a supportive, collaborative, and respectful environment where you can feel comfortable and empowered to explore your thoughts, feelings, and behaviors.'",
    source: false,
    sourceLink: "",
    standaloneTweets: ["1806877777137660143", "1806865542873039269"],
    thenVsNowFormat: false,
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2024-06-28",
    claimIds: ["30x", "3"],
    exampleId: "00000030x08",
    keywordIds: [],
    text: "Double-murder of an Israeli couple is 'an act of love.' An American/Israeli couple, Sarah Milgrim and Yaron Lischinksy, were murdered outside a Jewish event in Washington, DC in May 2025. According to the charges, Sarah Milgrim, badly wounded, tried to crawl away from the killer. The killer followed her, firing repeatedly until he emptied his weapon and she was dead. This murder is called an 'act of love' by antizionist group 'Unity of Fields' (formerly called 'Palestine Action US'). The antizionist who murdered the couple is a “political prisoner.” The group circulated the killer's manifesto and defended “armed resistance.”",
    source: false,
    sourceLink: "",
    standaloneTweets: ["1926123113026121853", "1925671899603841322"],
    thenVsNowFormat: false,
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2023-12-09",
    claimIds: ["30x", "11"],
    exampleId: "00000030x09",
    keywordIds: ["MehdiHasan"],
    text: "Mehdi Hasan provides platform for nonstop, one-sided, repeated Israel bashing, generic or one-sided 'war crimes' accusations, then clutches pearls and 'condemns' a gun being fired outside a synogague. The nonstop, one-sided Israel bashing leads to the violence and they can not be separated. This is the rhetorical game. Oct. 13: Human Rights Watch launders an accusaion that Israel violated international law by using white phosphorous, and Mehdi retweets it (white phosphorous shells can legally be used as a smokescreen under international law, which is how Israel uses it). Oct. 22: AOC accuses Israel of 'war crimes' on Mehdi's show. Oct. 31: ReTweets Joy Reid's one-sided narrative blaming Israel solely without alternative. Nov. 5: Jamaal Bowman says Israel is committing 'war crimes' on Mehdi's show. ",
    source: false,
    sourceLink: "",
    standaloneTweets: [],
    thenVsNowFormat: true,
    thenTweets: ["1712836770646183940", "2001401544063803884", "1719391017336480137", "1721486721169215640"],
    nowTweets:[],
    themTweets: [],
    usTweets: [],
    constellationFormat: true,
    constellationTweets: [{
      date: "",
      text: "Oct. 10, three days after the massacre, as Hamas terrorists are still roaming Israel, Mehdi Hassan starts the drumbeat.",
      source: false,
      sourceLink: "",
      tweetIds: "",
      rebuttalIds: "",
    }],
    constellationStandalone: ["1733211524338950471"]
  }
]

module.exports = { claim30x, examples30x };