const claim44 = {
  dateAdded: "",
  claimText: "Israel is a great country that treats Palestinians, including known terrorists. No other country in the Middle East comes even close to behaving with such humanity. It's innovation, tech, and medical advancements have benefitted all of humanity.",
  claimShortText: "Israel heroism, morality, and innovation",
  claimId: "44"
}

const examples44 = [
  {
    dateAdded: "",
    date: "2025-11-17",
    claimIds: ["44"],
    exampleId: "000004401",
    keywordIds: ["Innovation"],
    text: "Israeli startup Remilk, one of the world’s leading companies in cultured milk, will launch its animal-free milk in Israeli stores starting January 2026. Remilk uses fermentation to produce dairy proteins that are identical to cow’s milk- but made entirely without cows",
    standaloneTweets: ["1988048288210362723"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2025-12-02",
    claimIds: ["44", "41", "18"],
    exampleId: "000004402",
    keywordIds: [],
    text: "Israel's “Gift of Life” organization tried to register a world record celebrating 2,000 altruistic kidney donors who saved strangers' lives. Guinness accepted the fees, reviewed the materials, and then abruptly announced it no longer processes submissions from Israel.",
    standaloneTweets: ["1995956709005709495"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2025-12-03",
    claimIds: ["44"],
    exampleId: "000004403",
    keywordIds: ["Innovation"],
    text: "Israeli researchers believe they may have isolated the 'Holy Grail' cells which can slow down aging. 'T helper' blood cells may hold the secret to longevity.",
    standaloneTweets: ["1996393301998805271"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "1965-01-01",
    claimIds: ["44"],
    exampleId: "000004404",
    keywordIds: ["Innovation"],
    text: "Drip irrigation (1960s): Israeli engineer Simcha Blass noticed a tree thriving from a leaky pipe. He invented tubing that drips water straight to roots. Result? Israel grows fruit in the desert — and exports it. Now used on farms worldwide.",
    source: true,
    sourceLink: "https://www.dripworks.com/blog/drip-tubing-and-the-history-of-drip-irrigation?srsltid=AfmBOorSvjDi2dLw9Eiv2lABNN54piLxeIstAXpTUkvUObO8SvFPorCz",
    standaloneTweets: ["1956737212080681313"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2001-01-01",
    claimIds: ["44"],
    exampleId: "000004405",
    keywordIds: ["Innovation"],
    text: "PillCam (2001): ex-missile engineer Gavriel Iddan built a swallowable camera the size of a pill. It photographs the digestive tract, replacing invasive scopes. Millions have had painless diagnoses thanks to this Israeli invention.",
    source: true,
    sourceLink: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5438796/",
    standaloneTweets: ["1956737215129895192"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2011-01-01",
    claimIds: ["44"],
    exampleId: "000004406",
    keywordIds: ["Innovation"],
    text: "Iron Dome (2011): Brig. Gen. Daniel Gold led a team that built a missile shield with 90%+ success. Once doubted, it now saves lives daily. In seconds, rockets are detected, tracked, and destroyed mid-air.",
    source: true,
    sourceLink: "https://defensetech-week.com/speaker/brig-gen-res-dr-daniel-gold/",
    standaloneTweets: ["1956737218401415601"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2010-01-01",
    claimIds: ["44"],
    exampleId: "000004407",
    keywordIds: ["Innovation"],
    text: "Watergen (2010s): Arye Kohavi’s Israeli startup built machines that turn air humidity into clean drinking water. From African villages to disaster zones — entire communities now drink water pulled from the sky.",
    source: true,
    sourceLink: "https://www.i24news.tv/en/news/innov-nation/artc-from-air-to-water-israeli-startup-turns-humidity-into-drinking-water",
    standaloneTweets: ["1956737224072167743"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "1999-01-01",
    claimIds: ["44"],
    exampleId: "000004408",
    keywordIds: ["Innovation"],
    text: "USB Flash Drive (1999): Dov Moran, an Israeli engineer, lost a file when his laptop crashed. His fix? The USB stick. Portable memory that anyone can carry. It reshaped how the world stores and shares data.",
    source: true,
    sourceLink: "https://www.bbc.com/news/av/business-40706984",
    standaloneTweets: ["1956737227498967548"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2022-03-01",
    claimIds: ["44"],
    exampleId: "000004409",
    keywordIds: ["Innovation", "US partnership"],
    text: "Wastewater reuse is a large and growing source of water in Israel, accounting for greater than 25% of the country's water supply. Israel reuses 90% of their sewage for agricultural irrigation. By comparison, the U.S. reuses less than 10%.",
    source: true,
    sourceLink: "https://www.epa.gov/system/files/documents/2023-03/From%20Water%20Stressed%20to%20Water%20Secure%20-%20Lessons%20from%20Israel%27s%20Water%20Reuse%20Approach.pdf",
    standaloneTweets: ["1674932877614628864"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2023-04-04",
    claimIds: ["44"],
    exampleId: "000004410",
    keywordIds: ["Innovation"],
    text: "Israeli agricultural scientists have developed new crop varieties that are more resistant to heat, drought, and saline conditions",
    source: true,
    sourceLink: "https://themedialine.org/life-lines/israeli-scientists-develop-drought-resistant-tomatoes-in-response-to-climate-change/",
    standaloneTweets: ["1674932878919053312"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2025-11-04",
    claimIds: ["44"],
    exampleId: "000004411",
    keywordIds: ["Innovation"],
    text: "In breakthrough, Israeli researchers detect Parkinson’s markers 15 years before symptoms",
    source: true,
    sourceLink: "https://www.timesofisrael.com/in-breakthrough-israeli-researchers-detect-parkinsons-markers-15-years-before-symptoms/",
    standaloneTweets: ["1838933861830381831"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2020-11-22",
    claimIds: ["44"],
    exampleId: "000004412",
    keywordIds: ["Innovation"],
    text: "Israeli scientists: New cancer treatment like using 'tiny scissors' to hit cells",
    source: true,
    sourceLink: "https://nypost.com/2020/11/22/new-cancer-treatment-like-using-tiny-scissors-to-target-cells/?utm_source=NYPTwitter&utm_campaign=SocialFlow&utm_medium=SocialFlow",
    standaloneTweets: ["1330654450705457155"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2026-02-22",
    claimIds: ["44"],
    exampleId: "000004413",
    keywordIds: [],
    text: "Jewish hockey player Jack Hughes scores the game-winning goal to win Olympic gold for Team USA.",
    source: false,
    standaloneTweets: ["2025604630722261347"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2025-11-03",
    claimIds: ["44"],
    exampleId: "000004414",
    keywordIds: [],
    text: "Israeli doctors at Kaplan Medical Center have performed the first-ever implant of a fully artificial corneal endothelium - restoring a patient’s sight without the need for donor tissue. The ultra-thin EndoArt device, developed by Israeli company EyeYon Medical, replaces the function of the cornea’s inner cell layer, which cannot regenerate naturally and is essential for clear vision. With more than 13 million people worldwide waiting for corneal transplants, this innovation offers a scalable, donor-free alternative - underscoring Israel’s amazing record of achievement in innovating life-changing medical technologies. The patient who received the transplant had already undergone three failed donor cornea transplants, and was no longer eligible for traditional treatment due to the likelihood of further rejection. Unlike traditional grafts, the EndoArt implant is bio-inert - meaning the body cannot reject it - and the procedure is short and minimally invasive. For patients with failed grafts or high rejection risk, this synthetic solution offers a new, potentially sight-restoring option.",
    source: true,
    sourceLink: "https://www.jpost.com/health-and-wellness/article-872530",
    standaloneTweets: ["1986214945990541340"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2026-02-10",
    claimIds: ["44"],
    exampleId: "000004415",
    keywordIds: [],
    text: "Researchers from top Israeli and US universities unveiled a pioneering “living” biological implant—a self-regulating device that senses glucose levels, produces insulin inside the body, and uses a novel “crystalline shield” to evade immune rejection. This breakthrough could eliminate daily insulin injections for millions with Type 1 diabetes, representing a major advance in regenerative medicine and long-term diabetes treatment. The multinational team included partners from MIT, Harvard, Johns Hopkins, and others.",
    source: true,
    sourceLink: "https://technionuk.org/news-post/israeli-led-research-unveils-living-implant-that-could-end-insulin-shots/",
    standaloneTweets: ["2021161863958950040"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2026-02-22",
    claimIds: ["44"],
    exampleId: "000004416",
    keywordIds: [],
    text: "Scientists at Rambam Health Care College have developed a novel deep-brain stimulation approach that may restore cognitive flexibility in people with schizophrenia - a condition affecting 21 million worldwide. Led by Dr. Nir Asch under the guidance of Israel Prize laureate Hagai Bergman from Hebrew University, the peer-reviewed study published in Nature found that targeted brain stimulation reversed key symptoms in preclinical trials.",
    source: true,
    sourceLink: "https://www.timesofisrael.com/in-breakthrough-israeli-scientists-use-deep-brain-stimulation-to-counter-schizophrenia/",
    standaloneTweets: ["2025662377480397144"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2026-01-20",
    claimIds: ["44"],
    exampleId: "000004417",
    keywordIds: [],
    text: "GluFormer, a transformer model trained on 10M+ glucose readings, predicts diabetes and cardiovascular risk up to 12 years ahead - outperforming HbA1c. Built by NVIDIA Israel, Weizmann Science,  and clinical partners.",
    source: true,
    sourceLink: "https://www.calcalistech.com/ctechnews/article/sjwwjphbwg?ncid=so-twit-170539&linkId=100000403548689#google_vignette",
    standaloneTweets: ["2013677993479090438"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2025-12-26",
    claimIds: ["44"],
    exampleId: "000004418",
    keywordIds: [],
    text: "Israeli scientists have made a groundbreaking discovery with the potential to treat cardiac fibrosis, which currently has no method of reversing damage.",
    source: true,
    sourceLink: "https://www.timesofisrael.com/in-surprising-breakthrough-scientists-in-israel-find-cancer-may-help-heal-the-failing-heart/",
    standaloneTweets: ["2004935088438489558"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2025-12-18",
    claimIds: ["44"],
    exampleId: "000004419",
    keywordIds: [],
    text: "Israeli, US scientists uncover new RNA molecule enabling phages to hijack bacteria more efficiently, advancing treatments for antibiotic-resistant infections.",
    source: true,
    sourceLink: "https://www.jpost.com/science/article-880658",
    standaloneTweets: ["2001687611736531167"],
    themTweets: [],
    usTweets: []
  },
  {
    dateAdded: "",
    date: "2025-12-21",
    claimIds: ["44"],
    exampleId: "000004420",
    keywordIds: [],
    text: "ISRAEL SAVES SYRIAN DRUZE TODDLER | A Druze mother fled war-torn Syria so her baby could get life-saving heart surgery in Israel. At Wolfson, Jewish & Arab doctors treated her child free of charge through Save a Child’s Heart. “Here there is peace. I wish we could live like this,” she said.",
    source: true,
    sourceLink: "https://www.jns.org/israel-news/saving-a-syrian-druze-childs-heart?utm_content=500579557&utm_medium=social&utm_source=twitter&hss_channel=tw-538525553",
    standaloneTweets: ["2002733292903158022"],
    themTweets: [],
    usTweets: []
  }
]

module.exports = { claim44, examples44 };